// Generates the palette accessibility report (Markdown) and the palette sheet
// (SVG) committed under docs/design/generated/. Tests compare the committed
// files with fresh output, so the docs can never drift from the code.

import { contrastRatio, deltaE, simulateVision, type VisionType } from "./color.js";
import { BOARD_SURFACES, PLAYER_IDENTITIES, TOKEN_HALO, type PlayerIdentity } from "./palette.js";
import { TOKEN_STATES, token2dSvg } from "./token2d.js";

export const VISION_TYPES: readonly VisionType[] = ["normal", "protanopia", "deuteranopia", "tritanopia"];

export interface PairDistance {
  a: string;
  b: string;
  deltaE: number;
}

/** All pairwise body-colour distances for a set of identities, as seen under `vision`. */
export function pairDistances(identities: readonly PlayerIdentity[], vision: VisionType): PairDistance[] {
  const out: PairDistance[] = [];
  for (let i = 0; i < identities.length; i++) {
    for (let j = i + 1; j < identities.length; j++) {
      const a = identities[i]!;
      const b = identities[j]!;
      out.push({ a: a.id, b: b.id, deltaE: deltaE(simulateVision(a.body, vision), simulateVision(b.body, vision)) });
    }
  }
  return out.sort((x, y) => x.deltaE - y.deltaE);
}

export function minDistance(identities: readonly PlayerIdentity[], vision: VisionType): PairDistance {
  return pairDistances(identities, vision)[0] ?? { a: "", b: "", deltaE: Infinity };
}

/** Worst-case contrast of a token's outline (rim or halo, whichever is better) on a surface. */
export function outlineContrast(identity: PlayerIdentity, surface: string): number {
  return Math.max(contrastRatio(identity.rim, surface), contrastRatio(TOKEN_HALO, surface));
}

/** Every surface a token can stand on: plain cells and every identity's lane/start fill. */
export function tokenSurfaces(): string[] {
  return [BOARD_SURFACES.cell, BOARD_SURFACES.base, ...PLAYER_IDENTITIES.map((p) => p.lane), ...PLAYER_IDENTITIES.map((p) => p.body)];
}

const fmt = (n: number, digits = 1) => n.toFixed(digits);

const escapeXml = (text: string) =>
  text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function buildPaletteReport(): string {
  const lines: string[] = [
    "<!-- Generated by `npm run design:generate` from packages/design-tokens. Do not edit by hand. -->",
    "",
    "# Player identity palette — measured accessibility report",
    "",
    `Board cell \`${BOARD_SURFACES.cell}\` · board base \`${BOARD_SURFACES.base}\` · contrast = WCAG 2.x ratio · ΔE = CIEDE2000 · colour-blindness simulated with Machado et al. (2009) at full severity.`,
    "",
    "## Identities",
    "",
    "| Seat | Identity | Symbol | Body | Rim | Highlight | Lane | Ink | Rim vs cell | Ink vs body | Worst outline contrast | ΔE body vs cell |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  const surfaces = tokenSurfaces();
  for (const p of PLAYER_IDENTITIES) {
    const worstOutline = Math.min(...surfaces.map((s) => outlineContrast(p, s)));
    lines.push(
      `| ${p.seat} | ${p.name} | ${p.symbol} | \`${p.body}\` | \`${p.rim}\` | \`${p.highlight}\` | \`${p.lane}\` | \`${p.ink}\` | ${fmt(contrastRatio(p.rim, BOARD_SURFACES.cell))}:1 | ${fmt(contrastRatio(p.ink, p.body))}:1 | ${fmt(worstOutline)}:1 | ${fmt(deltaE(p.body, BOARD_SURFACES.cell), 0)} |`,
    );
  }

  lines.push("", "## Distinctness of body colours", "", "| Vision | All 15: closest pair (ΔE) | All 15: pairs below ΔE 10 | Classic 4: closest pair (ΔE) |", "| --- | --- | --- | --- |");
  const classic = PLAYER_IDENTITIES.slice(0, 4);
  for (const vision of VISION_TYPES) {
    const all = minDistance(PLAYER_IDENTITIES, vision);
    const close = pairDistances(PLAYER_IDENTITIES, vision).filter((d) => d.deltaE < 10);
    const c4 = minDistance(classic, vision);
    lines.push(
      `| ${vision} | ${all.a} / ${all.b} (${fmt(all.deltaE)}) | ${close.length === 0 ? "none" : close.map((d) => `${d.a}/${d.b} ${fmt(d.deltaE)}`).join(", ")} | ${c4.a} / ${c4.b} (${fmt(c4.deltaE)}) |`,
    );
  }

  lines.push("", "## Default seat sets (first N identities)", "", "| Players | Normal | Protanopia | Deuteranopia | Tritanopia |", "| --- | --- | --- | --- | --- |");
  for (let n = 2; n <= PLAYER_IDENTITIES.length; n++) {
    const set = PLAYER_IDENTITIES.slice(0, n);
    lines.push(`| ${n} | ${VISION_TYPES.map((v) => fmt(minDistance(set, v).deltaE)).join(" | ")} |`);
  }
  lines.push(
    "",
    "Values are the smallest ΔE between any two seats. Below ~10 colours can be confused at a glance; every seat therefore also carries a unique symbol, and player chips always show name + symbol.",
    "",
  );
  return lines.join("\n");
}

const CELL = 84;

/** Visual swatch sheet: every token on the board cell and on its own lane, under four vision types, plus all states. */
export function buildPaletteSheetSvg(): string {
  const columns: { label: string; vision: VisionType; onLane: boolean }[] = [
    { label: "Normal", vision: "normal", onLane: false },
    { label: "On own lane", vision: "normal", onLane: true },
    { label: "Protanopia", vision: "protanopia", onLane: false },
    { label: "Deuteranopia", vision: "deuteranopia", onLane: false },
    { label: "Tritanopia", vision: "tritanopia", onLane: false },
  ];
  const left = 170;
  const top = 56;
  const rows = PLAYER_IDENTITIES.length;
  const stateTop = top + rows * CELL + 56;
  const width = left + columns.length * CELL + 24;
  const height = stateTop + CELL + 40;
  const parts: string[] = [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${Math.max(width, left + TOKEN_STATES.length * CELL + 24)} ${height}" font-family="Inter, system-ui, sans-serif">`,
    `<rect width="100%" height="100%" fill="${BOARD_SURFACES.base}"/>`,
  ];
  columns.forEach((col, c) => {
    parts.push(`<text x="${left + c * CELL + CELL / 2}" y="${top - 16}" font-size="12" text-anchor="middle" fill="#141821">${col.label}</text>`);
  });
  PLAYER_IDENTITIES.forEach((p, r) => {
    const y = top + r * CELL;
    parts.push(`<text x="16" y="${y + CELL / 2 + 4}" font-size="13" fill="#141821">${p.seat}. ${escapeXml(p.name)}</text>`);
    columns.forEach((col, c) => {
      const t = (hex: string) => simulateVision(hex, col.vision);
      const x = left + c * CELL;
      const bg = col.onLane ? p.lane : BOARD_SURFACES.cell;
      parts.push(`<rect x="${x + 4}" y="${y + 4}" width="${CELL - 8}" height="${CELL - 8}" rx="8" fill="${t(bg)}" stroke="${t(BOARD_SURFACES.line)}"/>`);
      parts.push(`<svg x="${x + 12}" y="${y + 12}" width="${CELL - 24}" height="${CELL - 24}" viewBox="-6 -6 112 112">${token2dSvg(p, { idPrefix: `c${c}`, transform: t })}</svg>`);
    });
  });
  const demo = PLAYER_IDENTITIES[0]!;
  parts.push(`<text x="16" y="${stateTop - 16}" font-size="13" fill="#141821">Token states (${escapeXml(demo.name)})</text>`);
  TOKEN_STATES.forEach((state, i) => {
    const x = left + i * CELL;
    parts.push(`<rect x="${x + 4}" y="${stateTop + 4}" width="${CELL - 8}" height="${CELL - 8}" rx="8" fill="${BOARD_SURFACES.cell}" stroke="${BOARD_SURFACES.line}"/>`);
    parts.push(`<svg x="${x + 12}" y="${stateTop + 8}" width="${CELL - 24}" height="${CELL - 24}" viewBox="-6 -6 112 112">${token2dSvg(demo, { state, idPrefix: "st" })}</svg>`);
    parts.push(`<text x="${x + CELL / 2}" y="${stateTop + CELL + 8}" font-size="11" text-anchor="middle" fill="#5C6370">${state}</text>`);
  });
  parts.push("</svg>");
  return parts.join("\n");
}
