// The classic board's approved-reference table: every seat's step → cell
// mapping and a complete sample journey. Generated from the layout and
// topology; engine and renderer tests must agree with it.

import { CLASSIC_TOPOLOGY } from "../topology.js";
import { CLASSIC_SEATS, CLASSIC_TRACK, classicSeatPath } from "../classicSquareLayout.js";
import { cellKey } from "../layoutTypes.js";

const SEAT_NAMES = ["Crimson (top-left)", "Royal Blue (top-right)", "Emerald (bottom-right)", "Golden Yellow (bottom-left)"];

/** Opening 6, then rolls that total exactly 56 — illustrates the exact-finish rule. */
export const SAMPLE_JOURNEY_ROLLS = [6, 6, 5, 6, 4, 6, 5, 6, 3, 6, 3, 2, 4] as const;

function note(seat: number, step: number): string {
  const t = CLASSIC_TOPOLOGY;
  if (step === 0) return "start (safe)";
  if (step <= t.lastTrackStep) {
    const abs = (t.startIndex[seat]! + step) % t.trackLength;
    const startOwner = t.startIndex.indexOf(abs);
    if (step === t.lastTrackStep) return "turn-in";
    if (startOwner >= 0) return `start of seat ${startOwner + 1} (safe)`;
    if (t.safeIndices.includes(abs)) return "star (safe)";
    return "";
  }
  return step === t.finishStep ? "finish" : "home lane";
}

export function buildClassicReference(): string {
  const t = CLASSIC_TOPOLOGY;
  const paths = Array.from({ length: CLASSIC_SEATS }, (_, s) => classicSeatPath(s));
  const cellAt = (seat: number, step: number) => {
    const p = paths[seat]!;
    if (step <= t.lastTrackStep) return cellKey(p.track[step]!);
    if (step < t.finishStep) return cellKey(p.lane[step - t.lastTrackStep - 1]!);
    return `centre (${cellKey(p.finish)})`;
  };
  const absAt = (seat: number, step: number) => (step <= t.lastTrackStep ? String((t.startIndex[seat]! + step) % t.trackLength) : "—");

  const out: string[] = [
    "<!-- Generated by `npm run design:generate` from packages/board-layouts. Do not edit by hand. -->",
    "",
    "# Classic board — reference step table",
    "",
    `Clockwise. Track ${t.trackLength} cells; each seat moves steps 0–${t.lastTrackStep} on the track, ${t.lastTrackStep + 1}–${t.finishStep - 1} in its lane, and finishes at ${t.finishStep}. Cells are \`r<row>c<col>\` on the 15×15 grid (r0 = top). Abs = absolute track index.`,
    "",
    `| Step | ${SEAT_NAMES.map((n) => `${n} cell`).join(" | ")} | Abs (seat 1 / 2 / 3 / 4) | Note (seat 1) |`,
    `| --- | ${SEAT_NAMES.map(() => "---").join(" | ")} | --- | --- |`,
  ];
  for (let step = 0; step <= t.finishStep; step++) {
    const abs = Array.from({ length: CLASSIC_SEATS }, (_, s) => absAt(s, step)).join(" / ");
    out.push(`| ${step} | ${Array.from({ length: CLASSIC_SEATS }, (_, s) => cellAt(s, step)).join(" | ")} | ${abs} | ${note(0, step)} |`);
  }

  out.push(
    "",
    "Never visited by its owner: the cell just behind each start — " +
      Array.from({ length: CLASSIC_SEATS }, (_, s) => `seat ${s + 1} ${cellKey(CLASSIC_TRACK[(t.startIndex[s]! + t.trackLength - 1) % t.trackLength]!)}`).join(", ") +
      ".",
    "",
    "## Sample journey (identical for every colour)",
    "",
    `Rolls: ${SAMPLE_JOURNEY_ROLLS.join(", ")}. The first 6 opens the token onto its start (step 0); the remaining rolls total exactly ${t.finishStep}.`,
    "",
    `| Roll | Step | ${SEAT_NAMES.map((n) => n.split(" (")[0]).join(" | ")} |`,
    `| --- | --- | ${SEAT_NAMES.map(() => "---").join(" | ")} |`,
  );
  let step = -1;
  for (const roll of SAMPLE_JOURNEY_ROLLS) {
    step = step < 0 ? 0 : step + roll;
    out.push(`| ${roll} | ${step} | ${Array.from({ length: CLASSIC_SEATS }, (_, s) => cellAt(s, step)).join(" | ")} |`);
  }
  out.push(
    "",
    `At step 52 the token needs exactly ${t.finishStep - 52}: a 5 or 6 would overshoot ${t.finishStep} and is not a legal move for that token.`,
    "",
  );
  return out.join("\n");
}
