// Geometry report for every player count, generated from the topology so the
// numbers in docs/design/generated/geometry-report.md can never drift.

import { BOARD_SHAPE_BY_PLAYER_COUNT, PLAYER_COUNTS, TOKENS_PER_PLAYER, type PlayerCount } from "@ludo/shared-types";
import { topologyFor, type BoardTopology } from "../topology.js";

/** Token diameter is 0.82 of a cell; symbols are legible from a 24 px token (see token-sizes.svg). */
export const TOKEN_TO_CELL = 0.82;
export const MIN_LEGIBLE_TOKEN_PX = 24;
export const MIN_COMFORT_CELL_PX = Math.ceil(MIN_LEGIBLE_TOKEN_PX / TOKEN_TO_CELL); // 30

/** Board area (px) available on each reference device after chrome (see ui-*.md). */
export const DEVICE_BOARD_AREAS = [
  { id: "phone-360", label: "360×800 phone", w: 328, h: 624 },
  { id: "phone-390", label: "390×844 phone", w: 358, h: 668 },
  { id: "tablet", label: "1024×768 tablet", w: 676, h: 720 },
  { id: "desktop", label: "1920×1080 desktop", w: 1272, h: 968 },
] as const;

export interface BoardExtent {
  width: number;
  height: number;
  estimated: boolean;
}

/** Board size in cells (including frame). Classic and rectangle are exact grids; others are geometric estimates until Phase 5. */
export function boardExtent(t: BoardTopology): BoardExtent {
  switch (t.variant) {
    case "classic-square":
      return { width: 15, height: 15, estimated: false };
    case "rectangle":
      return { width: 19, height: 9, estimated: false };
    case "triangle": {
      // Three-arm "Y" with arm tips pointing into the vertices: hub ~1.7 + arm 8 + 3.5 vertex clearance.
      const circumradius = 1.7 + 8 + 3.5;
      return { width: round1(Math.sqrt(3) * circumradius), height: round1(1.5 * circumradius), estimated: true };
    }
    case "ring": {
      const n = t.sides;
      const inradius = t.segmentLength / (2 * Math.tan(Math.PI / n));
      const outer = (inradius + 0.5) / Math.cos(Math.PI / n) + 1.2;
      return { width: round1(2 * outer), height: round1(2 * outer), estimated: true };
    }
  }
}

const round1 = (v: number) => Math.round(v * 10) / 10;

/** Pixels per cell when the whole board fits the area (rectangles may rotate to fit). */
export function pxPerCell(extent: BoardExtent, area: { w: number; h: number }): number {
  const upright = Math.min(area.w / extent.width, area.h / extent.height);
  const rotated = Math.min(area.w / extent.height, area.h / extent.width);
  return Math.max(upright, rotated);
}

function safeDescription(t: BoardTopology): string {
  const offsets = t.safeIndices.filter((i) => i < t.segmentLength);
  const parts = offsets.map((o) => (o === 0 ? "start" : `+${o}`));
  return `${parts.join(", ")} per seat`;
}

export function buildGeometryReport(): string {
  const rows: string[] = [
    "<!-- Generated by `npm run design:generate` from packages/board-layouts. Do not edit by hand. -->",
    "",
    "# Board geometry report, 2–15 players",
    "",
    `Distance = moves from the start cell (step 0) to the finish with an exact roll; opening a token additionally needs a 6. Lane = ${topologyFor(4).laneLength} cells for every board. Track cells per side: ring boards have one seat segment per side; the square, rectangle and triangle fold each segment around an arm.`,
    "",
    "| Players | Shape | Variant | Sides | Shared track | Cells per seat segment | Distance per player | Safe cells | Safe pattern | Density | Lane | Max tokens | Board (cells) |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  const all: [string, BoardTopology, PlayerCount][] = [
    ...PLAYER_COUNTS.map((n) => [String(n), topologyFor(n), n] as [string, BoardTopology, PlayerCount]),
    ["2 (square option)", topologyFor(2, { twoPlayerBoard: "square" }), 2],
  ];
  for (const [label, t, n] of all) {
    const e = boardExtent(t);
    const shape = t.variant === "classic-square" ? "square" : BOARD_SHAPE_BY_PLAYER_COUNT[n];
    rows.push(
      `| ${label} | ${shape} | ${t.variant} | ${t.sides} | ${t.trackLength} | ${t.segmentLength} | ${t.finishStep} | ${t.safeIndices.length} | ${safeDescription(t)} | ${((t.safeIndices.length / t.trackLength) * 100).toFixed(1)}% | ${t.laneLength} | ${t.activeSeats.length * TOKENS_PER_PLAYER} | ${e.width} × ${e.height}${e.estimated ? " (est.)" : ""} |`,
    );
  }

  rows.push(
    "",
    "## Readability per device",
    "",
    `A token is legible (symbol recognisable) from ${MIN_LEGIBLE_TOKEN_PX} px, which needs a ${MIN_COMFORT_CELL_PX} px cell. Values are px per cell with the whole board visible; **zoom** is the magnification the focus view needs to reach ${MIN_COMFORT_CELL_PX} px cells.`,
    "",
    `| Players | ${DEVICE_BOARD_AREAS.map((d) => d.label).join(" | ")} | Phone (390) zoom | Phone verdict |`,
    `| --- | ${DEVICE_BOARD_AREAS.map(() => "---").join(" | ")} | --- | --- |`,
  );
  for (const [label, t] of all) {
    const e = boardExtent(t);
    const values = DEVICE_BOARD_AREAS.map((d) => pxPerCell(e, d));
    const phone = values[1]!;
    const zoom = Math.max(1, MIN_COMFORT_CELL_PX / phone);
    const verdict =
      phone >= MIN_COMFORT_CELL_PX
        ? "full board playable"
        : phone >= MIN_COMFORT_CELL_PX / 1.6
          ? "playable; move tray + light zoom"
          : "overview only; move tray + focus view required";
    rows.push(`| ${label} | ${values.map((v) => v.toFixed(1)).join(" | ")} | ${zoom === 1 ? "—" : `${zoom.toFixed(1)}×`} | ${verdict} |`);
  }
  rows.push(
    "",
    "Touch input never depends on these cell sizes: legal moves are always selectable from the move tray (≥ 56 px targets); see docs/design/interaction-crowded-boards.md.",
    "",
  );
  return rows.join("\n");
}
