// The city themes. Each one dresses the same classic board as a district of
// a real Indian metro: four colour corners become four neighbourhoods, a
// hero landmark stands on the horizon, and props, ground, light and voice
// give the city its character. All copy is original; landmark and prop
// assets are briefs for internal, procedural or placeholder art (nothing
// third-party, nothing generated without approval).
//
// Readability comes first: the board's cells stay light (see the tests),
// player colours never change, and renderers thin the dressing out on small
// screens (environment presets).

import type { AssetRef, AssetStatus, CityTheme, CityThemeId } from "./cityThemeTypes.js";

/** Landmarks and props are drawn in code as original 2D artwork (Batch B) unless marked "planned". */
const asset = (id: string, brief: string, status: AssetStatus = "procedural"): AssetRef => ({ id, status, brief });

const KOLKATA: CityTheme = {
  id: "kolkata",
  name: "Kolkata",
  nativeName: "কলকাতা",
  tagline: "Every move tells a story",
  descriptor: "Riverside heritage at golden hour: trams, yellow taxis, book stalls and adda by the Hooghly.",
  mood: ["heritage", "nostalgic", "literary", "warm", "riverside"],
  tone: "Poetic but playful; warm Bengali turns of phrase, never mocking.",
  palette: {
    sky: ["#F2B872", "#FBE3BD"],
    ground: "#C9A27E",
    groundAccent: "#8C5A3C",
    water: "#6F9C9E",
    boardFrame: "#6B3E26",
    boardCell: "#F7F2EC",
    boardLine: "#DCC9AB",
    accent: "#A8392A",
    accentInk: "#FFFFFF",
    surface: "#FBF1E4",
    ink: "#2A1A12",
  },
  districts: [
    { seat: 0, name: "College Street", motto: "Books · Adda · Ideas", feature: "A corner of open-air book stalls under arcades" },
    { seat: 1, name: "Hooghly Ghats", motto: "River · Rhythm · Flow", feature: "Riverside steps with a small temple pavilion" },
    { seat: 2, name: "The Maidan", motto: "Green · Open · Free", feature: "A green with old trees and a tram line along its edge" },
    { seat: 3, name: "Kumartuli", motto: "Craft · Colour · Celebration", feature: "Artisans' lane with clay-and-straw workshops" },
  ],
  landmarks: [
    { id: "howrah-bridge", name: "Howrah Bridge", role: "hero", placement: "horizon", asset: asset("kolkata.howrah-bridge", "Cantilever steel bridge silhouette across the river at sunset") },
    { id: "victoria-memorial", name: "Victoria Memorial", role: "supporting", placement: "edge", asset: asset("kolkata.victoria-memorial", "White marble domed hall, soft and distant") },
    { id: "riverside-temple", name: "Riverside temple spires", role: "supporting", placement: "corner", seat: 1, asset: asset("kolkata.riverside-temple", "Small Bengal-style temple spires on the ghats") },
  ],
  props: [
    { id: "tram", name: "Tram", kind: "vehicle", density: "low", asset: asset("kolkata.tram", "Two-car blue-and-white tram on inlaid tracks") },
    { id: "yellow-taxi", name: "Yellow taxi", kind: "vehicle", density: "low", asset: asset("kolkata.yellow-taxi", "Rounded classic yellow taxi, parked") },
    { id: "ferry", name: "River ferry", kind: "water", density: "low", asset: asset("kolkata.ferry", "Small ferry boats on the river") },
    { id: "gas-lamp", name: "Heritage lamp posts", kind: "street", density: "medium", asset: asset("kolkata.lamp", "Cast-iron lamp posts with warm light") },
    { id: "book-stall", name: "Book stalls", kind: "street", density: "low", asset: asset("kolkata.book-stall", "Wooden stalls stacked with books") },
    { id: "tea-stall", name: "Tea stall", kind: "street", density: "low", asset: asset("kolkata.tea-stall", "Tea stall with clay cups and a kettle", "planned") },
  ],
  groundPattern: { id: "laterite-tram-inlay", brief: "Warm laterite paving with brass tram-track inlays curving around the board" },
  signage: {
    wordmark: "KOLKATA",
    slogans: ["Same river, new moves", "Adda at every corner", "Every move tells a story"],
    script: { language: "bn", text: "চলুন, খেলা শুরু হোক", meaning: "Come on, let the game begin" },
  },
  reactions: [
    { moment: "six", description: "A tram bell rings once; warm lamp light brightens", cue: "kolkata.tram-bell" },
    { moment: "capture", description: "A brief shimmer runs across the river", cue: "kolkata.river-shimmer" },
    { moment: "home", description: "The bridge lights warm up for a moment", cue: "kolkata.conch-soft" },
    { moment: "victory", description: "Lamps along the ghats light one by one", cue: "kolkata.victory" },
  ],
  audio: { ambience: "kolkata.riverside-evening", cues: { "dice-roll": "common.die-wood", six: "kolkata.tram-bell", capture: "kolkata.river-shimmer", home: "kolkata.conch-soft", victory: "kolkata.victory" } },
  environmentPreset: "kolkata-golden-riverside",
  dialoguePack: "kolkata",
  emotionPack: "kolkata",
  preview: asset("kolkata.preview", "City card: bridge on the horizon over the river at golden hour", "procedural"),
};

const DELHI: CityTheme = {
  id: "delhi",
  name: "Delhi",
  nativeName: "दिल्ली",
  tagline: "Every move, a grand entrance",
  descriptor: "Sandstone, arches and ceremonial avenues: an imperial capital where old meets new.",
  mood: ["grand", "historical", "imperial", "energetic"],
  tone: "Bold and dramatic, with a Dilli swagger.",
  palette: {
    sky: ["#E7A877", "#F7DDC4"],
    ground: "#B9714F",
    groundAccent: "#E8D3B0",
    water: null,
    boardFrame: "#7A3B24",
    boardCell: "#F8F3EE",
    boardLine: "#DEC7AA",
    accent: "#8E2F1F",
    accentInk: "#FFFFFF",
    surface: "#FBEFE4",
    ink: "#2B1610",
  },
  districts: [
    { seat: 0, name: "Chandni Chowk", motto: "Spice · Bustle · Heart", feature: "Lanes of awnings and old havelis" },
    { seat: 1, name: "Kartavya Path", motto: "Grand · Ceremonial · Proud", feature: "A broad ceremonial avenue with lawns" },
    { seat: 2, name: "Lodhi Garden", motto: "Calm · Green · Timeless", feature: "Tombs among trees and lawns" },
    { seat: 3, name: "Hauz Khas", motto: "Old · New · Together", feature: "Ruins beside a lake and new cafés" },
  ],
  landmarks: [
    { id: "india-gate", name: "India Gate", role: "hero", placement: "horizon", asset: asset("delhi.india-gate", "Monumental sandstone arch at the end of a ceremonial avenue") },
    { id: "red-fort", name: "Red Fort", role: "supporting", placement: "edge", asset: asset("delhi.red-fort", "Red sandstone ramparts with domed pavilions") },
    { id: "qutub-minar", name: "Qutub Minar", role: "supporting", placement: "corner", seat: 3, asset: asset("delhi.qutub-minar", "Fluted, banded minaret tapering upward") },
  ],
  props: [
    { id: "auto", name: "Auto-rickshaw", kind: "vehicle", density: "low", asset: asset("delhi.auto", "Green-and-yellow auto-rickshaw") },
    { id: "metro", name: "Metro viaduct", kind: "architecture", density: "low", asset: asset("delhi.metro", "Elevated metro line in the distance", "planned") },
    { id: "arches", name: "Sandstone arches", kind: "architecture", density: "medium", asset: asset("delhi.arches", "Low sandstone arches lining the plaza", "planned") },
    { id: "kites", name: "Kites", kind: "nature", density: "low", asset: asset("delhi.kites", "A few kites high in the sky") },
    { id: "avenue-lamps", name: "Avenue lamps", kind: "street", density: "medium", asset: asset("delhi.lamps", "Ceremonial lamp posts") },
    { id: "canopy", name: "Canopy pavilion", kind: "architecture", density: "low", asset: asset("delhi.canopy", "Sandstone canopy pavilion on the avenue lawns") },
  ],
  groundPattern: { id: "sandstone-avenue", brief: "Red and buff sandstone paving with ceremonial avenue lines" },
  signage: {
    wordmark: "DELHI",
    slogans: ["Every move, a grand entrance", "Old roads, new moves", "Dil se, board par"],
    script: { language: "hi", text: "चलो, खेल शुरू", meaning: "Come on, the game begins" },
  },
  reactions: [
    { moment: "six", description: "The sandstone glows a shade warmer", cue: "delhi.drum-soft" },
    { moment: "capture", description: "The arch lights pulse once", cue: "delhi.capture" },
    { moment: "home", description: "Ceremonial lamps along the avenue brighten", cue: "delhi.home" },
    { moment: "victory", description: "A wave of kites rises over the arch", cue: "delhi.victory" },
  ],
  audio: { ambience: "delhi.avenue-dusk", cues: { "dice-roll": "common.die-wood", six: "delhi.drum-soft", capture: "delhi.capture", home: "delhi.home", victory: "delhi.victory" } },
  environmentPreset: "delhi-sandstone-dusk",
  dialoguePack: "delhi",
  emotionPack: "delhi",
  preview: asset("delhi.preview", "City card: the arch at the end of an avenue, a minaret beside it", "procedural"),
};

const CHENNAI: CityTheme = {
  id: "chennai",
  name: "Chennai",
  nativeName: "சென்னை",
  tagline: "Graceful moves by the shore",
  descriptor: "Temple towers, kolam patterns and the long sweep of the Marina in warm coastal light.",
  mood: ["coastal", "classical", "elegant", "grounded"],
  tone: "Calm but competitive; graceful, rooted Tamil warmth.",
  palette: {
    sky: ["#8CC6D6", "#F8E6C4"],
    ground: "#E3CBA0",
    groundAccent: "#C4572E",
    water: "#2E8BA0",
    boardFrame: "#7B4A2A",
    boardCell: "#F6F3EE",
    boardLine: "#E3D3B6",
    accent: "#0F6873",
    accentInk: "#FFFFFF",
    surface: "#EFF7F5",
    ink: "#122A2E",
  },
  districts: [
    { seat: 0, name: "Mylapore", motto: "Temple · Tradition · Tune", feature: "A temple tank with a carved gopuram behind" },
    { seat: 1, name: "Marina", motto: "Sea · Breeze · Sunrise", feature: "The promenade and the beach beyond" },
    { seat: 2, name: "Adyar", motto: "Green · Calm · Learning", feature: "Banyan shade by the estuary" },
    { seat: 3, name: "T. Nagar", motto: "Silk · Gold · Celebration", feature: "Festive shopfronts and garlands" },
  ],
  landmarks: [
    { id: "gopuram", name: "Temple gopuram", role: "hero", placement: "horizon", asset: asset("chennai.gopuram", "Tiered, ornamented temple tower in warm ochre") },
    { id: "lighthouse", name: "Marina lighthouse", role: "supporting", placement: "edge", asset: asset("chennai.lighthouse", "Tall coastal lighthouse by the sea") },
    { id: "heritage-hall", name: "Indo-Saracenic hall", role: "supporting", placement: "corner", seat: 3, asset: asset("chennai.heritage-hall", "Red-brick civic hall with domes") },
  ],
  props: [
    { id: "catamaran", name: "Fishing boats", kind: "water", density: "low", asset: asset("chennai.catamaran", "Wooden fishing boats on the sand") },
    { id: "kolam", name: "Kolam", kind: "street", density: "medium", asset: asset("chennai.kolam", "White rice-flour kolam patterns on the paving") },
    { id: "coffee-stall", name: "Filter coffee stall", kind: "street", density: "low", asset: asset("chennai.coffee", "Stall with brass tumblers", "planned") },
    { id: "coconut-palms", name: "Coconut palms", kind: "nature", density: "medium", asset: asset("chennai.palms", "Palms swaying in the sea breeze") },
    { id: "bell", name: "Temple bell", kind: "architecture", density: "low", asset: asset("chennai.bell", "Bronze bell in a small mandapam", "planned") },
  ],
  groundPattern: { id: "kolam-granite", brief: "Pale granite with kolam-inspired chalk patterns between the corners" },
  signage: {
    wordmark: "CHENNAI",
    slogans: ["Graceful moves by the shore", "Calm hands, sharp moves", "Every tide, a new turn"],
    script: { language: "ta", text: "வாங்க, விளையாடலாம்", meaning: "Come, let's play" },
  },
  reactions: [
    { moment: "six", description: "A temple bell chimes softly", cue: "chennai.temple-bell" },
    { moment: "capture", description: "A sea breeze ripples through the palms", cue: "chennai.breeze" },
    { moment: "home", description: "Kolam lines glow briefly around the finish", cue: "chennai.home" },
    { moment: "victory", description: "The lighthouse beam sweeps across the board", cue: "chennai.victory" },
  ],
  audio: { ambience: "chennai.marina-morning", cues: { "dice-roll": "common.die-wood", six: "chennai.temple-bell", capture: "chennai.breeze", home: "chennai.home", victory: "chennai.victory" } },
  environmentPreset: "chennai-coastal-morning",
  dialoguePack: "chennai",
  emotionPack: "chennai",
  preview: asset("chennai.preview", "City card: a gopuram and a lighthouse over the sea", "procedural"),
};

const MUMBAI: CityTheme = {
  id: "mumbai",
  name: "Mumbai",
  nativeName: "मुंबई",
  tagline: "The big screen of moves",
  descriptor: "Seafront lights, art deco and local trains: a fast, cinematic city by the Arabian Sea.",
  mood: ["fast", "iconic", "cinematic", "ambitious", "coastal"],
  tone: "Hustle and swagger; filmi drama, always good-humoured.",
  palette: {
    sky: ["#46557F", "#EBA67C"],
    ground: "#9AA3A8",
    groundAccent: "#E3C77B",
    water: "#2F5D7C",
    boardFrame: "#2D3142",
    boardCell: "#F7F5EF",
    boardLine: "#D8D3C7",
    accent: "#1B4F8F",
    accentInk: "#FFFFFF",
    surface: "#EEF2F7",
    ink: "#141821",
  },
  districts: [
    { seat: 0, name: "Colaba", motto: "Sea · Street · Swagger", feature: "Waterfront arcades and street stalls" },
    { seat: 1, name: "Marine Drive", motto: "Lights · Waves · Night", feature: "The curved promenade and its lights" },
    { seat: 2, name: "Malabar Hill", motto: "Green · Height · Breeze", feature: "Hanging gardens above the bay" },
    { seat: 3, name: "Bandra", motto: "Dreams · Stars · Hustle", feature: "Seaside steps and murals" },
  ],
  landmarks: [
    { id: "gateway", name: "Gateway of India", role: "hero", placement: "horizon", asset: asset("mumbai.gateway", "Basalt arch with turrets facing the harbour") },
    { id: "sea-link", name: "Sea link", role: "supporting", placement: "edge", asset: asset("mumbai.sea-link", "Cable-stayed bridge over the bay") },
    { id: "terminus", name: "Heritage terminus", role: "supporting", placement: "corner", seat: 0, asset: asset("mumbai.terminus", "Gothic railway terminus with a central dome", "planned") },
  ],
  props: [
    { id: "local-train", name: "Local train", kind: "vehicle", density: "low", asset: asset("mumbai.local-train", "Suburban train passing behind the board") },
    { id: "taxi", name: "Black-and-yellow taxi", kind: "vehicle", density: "low", asset: asset("mumbai.taxi", "Classic black-and-yellow taxi") },
    { id: "deco-facades", name: "Art deco facades", kind: "architecture", density: "medium", asset: asset("mumbai.deco", "Pastel art deco buildings along the seafront") },
    { id: "promenade-lights", name: "Promenade lights", kind: "street", density: "medium", asset: asset("mumbai.lights", "A string of seafront lights") },
    { id: "monsoon-puddles", name: "Monsoon puddles", kind: "nature", density: "low", asset: asset("mumbai.puddles", "Reflective puddles on the promenade", "planned") },
  ],
  groundPattern: { id: "deco-promenade", brief: "Wet-stone promenade with art deco tile borders" },
  signage: {
    wordmark: "MUMBAI",
    slogans: ["The big screen of moves", "Full speed, full drama", "One more take, one more move"],
    script: { language: "mr", text: "चला, खेळ सुरू", meaning: "Come on, the game starts" },
  },
  reactions: [
    { moment: "six", description: "A glint runs along the skyline", cue: "mumbai.glint" },
    { moment: "capture", description: "The promenade lights pulse once", cue: "mumbai.lights-pulse" },
    { moment: "home", description: "A local train horn in the distance", cue: "mumbai.train-horn" },
    { moment: "victory", description: "The Queen's Necklace lights up end to end", cue: "mumbai.victory" },
  ],
  audio: { ambience: "mumbai.seafront-dusk", cues: { "dice-roll": "common.die-wood", six: "mumbai.glint", capture: "mumbai.lights-pulse", home: "mumbai.train-horn", victory: "mumbai.victory" } },
  environmentPreset: "mumbai-seafront-dusk",
  dialoguePack: "mumbai",
  emotionPack: "mumbai",
  preview: asset("mumbai.preview", "City card: the harbour arch and skyline at dusk over the sea", "procedural"),
};

const BENGALURU: CityTheme = {
  id: "bengaluru",
  name: "Bengaluru",
  nativeName: "ಬೆಂಗಳೂರು",
  tagline: "Smart moves in the garden city",
  descriptor: "Leafy boulevards, civic granite and café-lined streets in pleasant morning light.",
  mood: ["modern", "youthful", "green", "tech-forward", "calm"],
  tone: "Smart and friendly; easy Kannada-English banter.",
  palette: {
    sky: ["#A6D3E0", "#EAF6EC"],
    ground: "#8EA97B",
    groundAccent: "#5C6B73",
    water: null,
    boardFrame: "#3F4B3B",
    boardCell: "#F8FAF3",
    boardLine: "#D5DDCD",
    accent: "#1C6E46",
    accentInk: "#FFFFFF",
    surface: "#EFF6EE",
    ink: "#14231A",
  },
  districts: [
    { seat: 0, name: "MG Road", motto: "Buzz · Bites · Beats", feature: "Boulevard shops and a metro line overhead" },
    { seat: 1, name: "Vidhana Veedhi", motto: "Civic · Grand · Steady", feature: "Granite steps before a domed civic hall" },
    { seat: 2, name: "Cubbon Park", motto: "Green · Calm · Fresh", feature: "Bamboo groves and shaded walks" },
    { seat: 3, name: "Koramangala", motto: "Ideas · Cafés · Startups", feature: "Café terraces and a glass campus" },
  ],
  landmarks: [
    { id: "vidhana-soudha", name: "Vidhana Soudha", role: "hero", placement: "horizon", asset: asset("bengaluru.vidhana-soudha", "Granite civic building with a central dome, seen across a lawn") },
    { id: "glass-house", name: "Lalbagh glass house", role: "supporting", placement: "corner", seat: 2, asset: asset("bengaluru.glass-house", "Victorian glass house among trees") },
    { id: "tech-campus", name: "Tech campus", role: "supporting", placement: "edge", asset: asset("bengaluru.campus", "Low glass offices with soft lights") },
  ],
  props: [
    { id: "metro", name: "Metro", kind: "vehicle", density: "low", asset: asset("bengaluru.metro", "Purple metro on a viaduct", "planned") },
    { id: "rain-trees", name: "Rain trees", kind: "nature", density: "medium", asset: asset("bengaluru.trees", "Wide-canopied trees and flowering gulmohar") },
    { id: "darshini", name: "Darshini café", kind: "street", density: "low", asset: asset("bengaluru.darshini", "Standing café with steel tumblers") },
    { id: "cycles", name: "Cycles", kind: "vehicle", density: "low", asset: asset("bengaluru.cycles", "A few parked cycles", "planned") },
    { id: "led-paths", name: "Lit paths", kind: "street", density: "low", asset: asset("bengaluru.led-paths", "Subtle tech-blue path lights in the park") },
  ],
  groundPattern: { id: "granite-park", brief: "Grey granite pavers bordered by lawn and park paths" },
  signage: {
    wordmark: "BENGALURU",
    slogans: ["Smart moves in the garden city", "Calm city, quick moves", "Game on, maga"],
    script: { language: "kn", text: "ಬನ್ನಿ, ಆಟ ಶುರು", meaning: "Come, the game starts" },
  },
  reactions: [
    { moment: "six", description: "A soft tech-blue pulse runs along the park paths", cue: "bengaluru.pulse" },
    { moment: "capture", description: "Leaves rustle in a passing breeze", cue: "bengaluru.leaves" },
    { moment: "home", description: "The dome's lights brighten gently", cue: "bengaluru.home" },
    { moment: "victory", description: "Path lights ripple out from the finish", cue: "bengaluru.victory" },
  ],
  audio: { ambience: "bengaluru.park-morning", cues: { "dice-roll": "common.die-wood", six: "bengaluru.pulse", capture: "bengaluru.leaves", home: "bengaluru.home", victory: "bengaluru.victory" } },
  environmentPreset: "bengaluru-garden-morning",
  dialoguePack: "bengaluru",
  emotionPack: "bengaluru",
  preview: asset("bengaluru.preview", "City card: a domed civic building behind green trees", "procedural"),
};

/** The original, untheme'd table: the approved classic design. */
const CLASSIC: CityTheme = {
  id: "classic",
  name: "Classic",
  nativeName: null,
  tagline: "The table as you know it",
  descriptor: "The clean classic board, no city around it.",
  mood: ["clean", "focused"],
  tone: "Plain, friendly English.",
  palette: {
    sky: ["#F3F0EA", "#F3F0EA"],
    ground: "#F3F0EA",
    groundAccent: "#E2DCD1",
    water: null,
    boardFrame: "#FFFFFF",
    boardCell: "#F7F4EE",
    boardLine: "#D8D0C2",
    accent: "#1F5FD6",
    accentInk: "#FFFFFF",
    surface: "#FFFFFF",
    ink: "#141821",
  },
  districts: [
    { seat: 0, name: "Crimson", motto: "Bold · Bright · Brave", feature: "The crimson base" },
    { seat: 1, name: "Royal Blue", motto: "Calm · Clear · Steady", feature: "The blue base" },
    { seat: 2, name: "Emerald", motto: "Fresh · Quick · Keen", feature: "The emerald base" },
    { seat: 3, name: "Golden", motto: "Warm · Lucky · Sure", feature: "The golden base" },
  ],
  landmarks: [],
  props: [],
  groundPattern: { id: "plain", brief: "None: the classic table" },
  signage: { wordmark: "LUDO", slogans: ["Ludo, beautifully played together"], script: null },
  reactions: [],
  audio: { ambience: "none", cues: {} },
  environmentPreset: "classic-studio",
  dialoguePack: "classic",
  emotionPack: "classic",
  preview: asset("classic.preview", "City card: the classic board", "procedural"),
};

export const CITY_THEMES: Readonly<Record<CityThemeId, CityTheme>> = {
  classic: CLASSIC,
  kolkata: KOLKATA,
  delhi: DELHI,
  chennai: CHENNAI,
  mumbai: MUMBAI,
  bengaluru: BENGALURU,
};
